name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-docker-buildx@126d331dc69f4a1aa02452e374835e6a5d565613
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
        # Buildx version. Example: v0.3.0
        buildx-version: latest
        # QEMU static binaries Docker image version. Example: 4.2.0-7
        qemu-version: latest
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      uses: docker/login-action@v1.8.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build the Docker image
      run: |
        docker buildx build . --file Dockerfile \
        --tag jonasbg/garmin-connect:$(date '+%Y%m%d') \
        --tag jonasbg/garmin-connect:latest \
        --build-arg VERSION=${{github.ref}} \
        --build-arg BUILD_DATE=$(date '+%Y%m%d') \
        --build-arg GITHUB_REF=${GITHUB_SHA::8} \
        --platform linux/amd64,linux/arm64 \
        --push
